name: Build & Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: test
        run: chmod +x sysinfo 
             ./sysinfo
      - name: Release
        run: curl -H "Authorization: token $secrets.GITHUB_TOKEN" -H "Content-Type: application/octet-stream" --data-binary "sysinfo "https://uploads.github.com/repos/dephraiim/sysinfo/releases/1/assets?name=sysinfo"
